import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

const str = (val: any) => {
  if (!val) return '[]'
  if (Array.isArray(val)) return JSON.stringify(val)
  return String(val)
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    
    const brief = await prisma.brief.create({
      data: {
        companyName: body.companyName || null,
        companyEstablished: body.companyEstablished || null,
        companySize: body.companySize || null,
        industry: body.industry || null,
        industryOther: body.industryOther || null,
        companyDescription: body.companyDescription || null,
        companyLocation: body.companyLocation || null,
        companyWebsite: body.companyWebsite || null,
        companySocialMedia: body.companySocialMedia || null,
        contactName: body.contactName || null,
        contactPosition: body.contactPosition || null,
        contactPositionOther: body.contactPositionOther || null,
        contactEmail: body.contactEmail || null,
        contactPhone: body.contactPhone || null,
        contactWhatsApp: body.contactWhatsApp || null,
        vision: body.vision || null,
        mission: body.mission || null,
        uniqueSellingProposition: body.uniqueSellingProposition || null,
        brandPersonality: body.brandPersonality || null,
        brandPersonalityOther: body.brandPersonalityOther || null,
        targetAudienceDescription: body.targetAudienceDescription || null,
        audienceAge: body.audienceAge || null,
        audienceGender: body.audienceGender || null,
        audienceLocation: body.audienceLocation || null,
        audienceIncome: body.audienceIncome || null,
        audienceEducation: body.audienceEducation || null,
        audienceOccupation: body.audienceOccupation || null,
        audienceInterests: body.audienceInterests || null,
        audiencePainPoints: body.audiencePainPoints || null,
        audienceBehavior: body.audienceBehavior || null,
        audienceBuyingJourney: body.audienceBuyingJourney || null,
        audienceBuyingJourneySteps: str(body.audienceBuyingJourneySteps),
        competitors: body.competitors || null,
        competitorStrengths: body.competitorStrengths || null,
        competitorWeaknesses: body.competitorWeaknesses || null,
        differentiation: body.differentiation || null,
        primaryGoal: body.primaryGoal || null,
        primaryGoalOther: body.primaryGoalOther || null,
        secondaryGoals: str(body.secondaryGoals),
        secondaryGoalsOther: body.secondaryGoalsOther || null,
        kpis: str(body.kpis),
        kpisOther: body.kpisOther || null,
        successMetrics: body.successMetrics || null,
        timelineGoal: body.timelineGoal || null,
        websiteType: body.websiteType || null,
        websiteTypeOther: body.websiteTypeOther || null,
        websitePurpose: str(body.websitePurpose),
        websitePurposeOther: body.websitePurposeOther || null,
        customFeatures: body.customFeatures || null,
        productTypes: body.productTypes || null,
        productCount: body.productCount || null,
        taxRequirements: body.taxRequirements || null,
        designStyle: body.designStyle || null,
        designStyleOther: body.designStyleOther || null,
        existingBrandGuidelines: body.existingBrandGuidelines || null,
        logoFileName: body.logoFileName || null,
        logoLink: body.logoLink || null,
        designAvoid: body.designAvoid || null,
        customPages: body.customPages || null,
        navigationStructure: body.navigationStructure || null,
        navigationStructureOther: body.navigationStructureOther || null,
        contentReady: body.contentReady || null,
        toneOfVoice: body.toneOfVoice || null,
        toneOfVoiceOther: body.toneOfVoiceOther || null,
        contentTypesOther: body.contentTypesOther || null,
        multimediaNeedsOther: body.multimediaNeedsOther || null,
        customKeywords: body.customKeywords || null,
        socialMediaOther: body.socialMediaOther || null,
        analyticsOther: body.analyticsOther || null,
        domainStatus: body.domainStatus || null,
        hostingPreference: body.hostingPreference || null,
        hostingPreferenceOther: body.hostingPreferenceOther || null,
        performanceRequirements: body.performanceRequirements || null,
        accessibilityNeeds: body.accessibilityNeeds || null,
        accessibilityNeedsOther: body.accessibilityNeedsOther || null,
        browserSupportOther: body.browserSupportOther || null,
        customIntegrations: body.customIntegrations || null,
        apiRequirements: body.apiRequirements || null,
        dataProtection: body.dataProtection || null,
        desiredLaunchDate: body.desiredLaunchDate || null,
        milestones: body.milestones || null,
        budgetRange: body.budgetRange || null,
        paymentTerms: body.paymentTerms || null,
        paymentTermsOther: body.paymentTermsOther || null,
        maintenanceLevel: body.maintenanceLevel || null,
        maintenanceLevelOther: body.maintenanceLevelOther || null,
        legalRequirements: body.legalRequirements || null,
        contentHierarchy: body.contentHierarchy || null,
        ctaStrategy: body.ctaStrategy || null,
        userFlow: body.userFlow || null,
        successStories: body.successStories || null,
        oldSitePainPoints: body.oldSitePainPoints || null,
        trainingAudience: body.trainingAudience || null,
        communicationPrefs: body.communicationPrefs || null,
        multiRoleUsers: body.multiRoleUsers || null,
        localization: body.localization || null,
        offlineIntegration: body.offlineIntegration || null,
        dataMigration: body.dataMigration || null,
        backupStrategy: body.backupStrategy || null,
        performanceBenchmarks: body.performanceBenchmarks || null,
        accessibilitySpecifics: body.accessibilitySpecifics || null,
        futureRoadmap: body.futureRoadmap || null,
        scalabilityPlans: body.scalabilityPlans || null,
        abTesting: body.abTesting || null,
        printConsistency: body.printConsistency || null,
        partnership: body.partnership || null,
        additionalNotes: body.additionalNotes || null,
        howHeardAboutUs: body.howHeardAboutUs || null,
        howHeardAboutUsOther: body.howHeardAboutUsOther || null,
        referralName: body.referralName || null,
        
        hasEcommerce: body.hasEcommerce || false,
        inventoryManagement: body.inventoryManagement || false,
        logoProvided: body.logoProvided || false,
        copywritingNeeded: body.copywritingNeeded || false,
        photographyNeeded: body.photographyNeeded || false,
        videographyNeeded: body.videographyNeeded || false,
        seoNeeded: body.seoNeeded || false,
        contentMarketing: body.contentMarketing || false,
        emailMarketing: body.emailMarketing || false,
        sslNeeded: body.sslNeeded !== false,
        timelineFlexible: body.timelineFlexible || false,
        rushProject: body.rushProject || false,
        budgetFlexible: body.budgetFlexible || false,
        maintenanceNeeded: body.maintenanceNeeded || false,
        trainingNeeded: body.trainingNeeded || false,
        documentationNeeded: body.documentationNeeded || false,
        privacyPolicyNeeded: body.privacyPolicyNeeded || false,
        termsOfServiceNeeded: body.termsOfServiceNeeded || false,
        cookiePolicyNeeded: body.cookiePolicyNeeded || false,
        gdprCompliance: body.gdprCompliance || false,
        
        coreValues: str(body.coreValues),
        coreValuesOther: body.coreValuesOther || null,
        colorPalette: str(body.colorPalette),
        designReferences: str(body.designReferences),
        pages: str(body.pages),
        contentTypes: str(body.contentTypes),
        multimediaNeeds: str(body.multimediaNeeds),
        targetKeywords: str(body.targetKeywords),
        socialMediaIntegration: str(body.socialMediaIntegration),
        analyticsNeeded: str(body.analyticsNeeded),
        browserSupport: str(body.browserSupport),
        deviceSupport: str(body.deviceSupport),
        integrations: str(body.integrations),
        integrationsOther: body.integrationsOther || null,
        securityRequirements: str(body.securityRequirements),
        securityRequirementsOther: body.securityRequirementsOther || null,
        complianceNeeds: str(body.complianceNeeds),
        complianceNeedsOther: body.complianceNeedsOther || null,
        emotionalResponse: str(body.emotionalResponse),
        emotionalResponseOther: body.emotionalResponseOther || null,
        existingAssets: str(body.existingAssets),
        notificationPrefs: str(body.notificationPrefs),
      },
    })
    
    return NextResponse.json({ success: true, id: brief.id })
  } catch (e: any) {
    console.error('API Error:', e)
    return NextResponse.json({ error: e.message || 'Internal server error' }, { status: 500 })
  }
}

export async function GET() {
  try {
    const briefs = await prisma.brief.findMany({ orderBy: { createdAt: 'desc' } })
    return NextResponse.json(briefs)
  } catch (e: any) {
    console.error('GET Error:', e)
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}